name: ShinyItems
main: io.github.sipsi133.ShinyItems
authors: [sipsi133,Qveshn]
depend: [LightAPI]
version: ${project.version}
api-version: '1.13'
commands:
   shinyitems:
      description: ShinyItems base command.
      usage: /shinyitems