name: ShinyItems
main: io.github.sipsi133.ShinyItems
author: sipsi133
softdepend: [LightAPI]
version: ${project.version}
commands:
   shinyitems:
      description: ShinyItems base command.
      usage: /shinyitems